package at.kaufi.kantine.ui.theme

import androidx.compose.ui.graphics.Color

// Light theme colors
val LightPrimary = Color(0xFF029AA8)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFB2EBF2)
val LightOnPrimaryContainer = Color(0xFF00363A)
val LightSecondary = Color(0xFF1A237E)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFDBE1FF)
val LightOnSecondaryContainer = Color(0xFF001152)
val LightBackground = Color(0xFFFFF8F0)
val LightOnBackground = Color(0xFF1C1B1F)
val LightSurface = Color(0xFFFFFFFF)
val LightOnSurface = Color(0xFF1C1B1F)
val LightSurfaceVariant = Color(0xFFF0F0F0)
val LightOnSurfaceVariant = Color(0xFF49454F)
val LightError = Color(0xFFB00020)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFCD8DF)
val LightOnErrorContainer = Color(0xFF370009)
val LightOutline = Color(0xFF79747E)

// Dark theme colors
val DarkPrimary = Color(0xFF80DEEA)
val DarkOnPrimary = Color(0xFF00363A)
val DarkPrimaryContainer = Color(0xFF004D40)
val DarkOnPrimaryContainer = Color(0xFFB2EBF2)
val DarkSecondary = Color(0xFF7986CB)
val DarkOnSecondary = Color(0xFF001152)
val DarkSecondaryContainer = Color(0xFF0C1454)
val DarkOnSecondaryContainer = Color(0xFFDBE1FF)
val DarkBackground = Color(0xFF1a1a2e)
val DarkOnBackground = Color(0xFFE6E1E5)
val DarkSurface = Color(0xFF252536)
val DarkOnSurface = Color(0xFFE6E1E5)
val DarkSurfaceVariant = Color(0xFF2E2E3E)
val DarkOnSurfaceVariant = Color(0xFFCAC4D0)
val DarkError = Color(0xFFCF6679)
val DarkOnError = Color(0xFF370009)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFCD8DF)
val DarkOutline = Color(0xFF938F99)
