default_platform(:android)

platform :android do
  desc "Capture screenshots using screengrab"
  lane :screenshots do
    screengrab(
      app_package_name: "at.kaufi.kantine",
      app_apk_path: "app/build/outputs/apk/debug/app-debug.apk",
      tests_apk_path: "app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk",
      locales: ["de-DE", "en-US"],
      clear_previous_screenshots: true,
    )
  end
end
